config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get '/home', to: 'home#home'

  resources :groups do
    resources :memberships
  end
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :membership_id
end

app/models/group.rb
class Group < ApplicationRecord
  # has_many :users
  has_many :memberships
  has_many :users, through: :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_many :flights
  validates :user_id, uniqueness: { scope: :group_id, message: "can only join a group once" }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # has_many :groups
  has_many :memberships
  has_many :groups, through: :memberships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @memberships = Membership.where(user:current_user)
    @groups = Group.where()
  end

  def show
    @group = Group.find(params[:id])
    @memberships = Membership.where(group:@group)
    @membership = Membership.where(user:current_user, group:@group)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.save!
    redirect_to new_group_membership_path(@group)
  end

  def update

  end

  def edit

  end

  private

  def group_params
    params.require(:group).permit(:name, :inv_code, :user_id)
  end

  def group_params_to_update
    params.require(:group).permit(:name)
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def index

  end

  def new
    @group = Group.find(params[:group_id])
    @membership = Membership.new
    @count = Membership.where(group:@group).count
  end

  def create
    @membership = Membership.new(membership_params)
    @group = Group.find(params[:group_id])
    @count = Membership.where(group:@group).count
    @membership.group = @group
    if @count == 0
      @membership.user_id = current_user.id
    else
      @inv_code = @group.inv_code

      @user = User.new(params[:name])
      @user.save!
      @membership.user= @user
    end
    @membership.save!
    redirect_to group_membership_path(@group,@membership )
  end

  def show
    @group = Group.find(params[:group_id])
    @membership = Membership.find(params[:id])
    @memberships = Membership.where(group:@group)
  end

  def destroy

  end

  def membership_params
    params.require(:membership).permit( :departure, :travel_date, :return_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_new_group_form.html.erb
<div id="form_group">
  <%= form_for(group) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.text_field :inv_code, value: SecureRandom.hex(10).to_s, class: 'd-none' %>
    <%= f.text_field :user_id, value: current_user.id, class: 'd-none' %>
    <%= f.submit %>
  <% end %>
</div>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-12">
      <%= link_to groups_path, class: "btn btn-secondary" do %>
        <i class="fa-solid fa-arrow-left"></i> Back
      <% end %>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-12">
      <h2><%= @group.name %></h2>
      <!-- Edit Group Name -->
      <div class="mb-4">
        <%= form_with(model: @group, local: true) do |f| %>
          <div class="form-group">
            <%= f.label :name, "Group Name" %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <%= f.submit 'Update Group Name', class: 'btn btn-primary mt-2' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%console%>

app/views/groups/index.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-12">
      <h2>Your Groups</h2>
      <% if @memberships.any? %>
        <ul class="list-group">
          <% @memberships.each do |membership| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= membership.group.name %>
              <div>
                <%= link_to "Open", group_path(membership.group), class: "btn btn-info btn-sm" %>
              </div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>You have no groups yet.</p>
      <% end %>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-12">
      <%= link_to "New Group", new_group_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>
<%console%>

app/views/groups/new.html.erb
<div class="back-button">
  <%= link_to :back do %>
    <i class="fa-solid fa-arrow-left fa-2xl"></i>
  <% end %>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <h1 class="my-3">Create a Trip</h1>
      <%= render 'new_group_form', group: @group %>
    </div>
  </div>
</div>
<%console%>

app/views/groups/show.html.erb
<div class="back-button">
  <%= link_to :back do %>
    <i class="fa-solid fa-arrow-left fa-2xl"></i>
  <% end %>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12">
      <h1 class="my-3">Your Groups</h1>
      <ul><% @groups.each do |group|%>
          <li><%= group.name %><br>
            Edit Group</li>
        <%end%>
      </ul>
    </div>
    <div class="col-12">
      <h1 class="my-3">Create a Trip</h1>
      <form action="/groups/new">
        <label for="group">Create a Trip</label>
        <input class="form-inputs" type="text" name="group" placeholder = "Trip Name">
        <input type="submit" class="btn btn-primary">
      </form>
    </div>
  </div>
</div>
<%console%>

app/views/home/home.html.erb
<div class="home-screen overflow-auto">
  <div class="section">
    <div class="steps-title">
      <h2 class="d-flex text-center justify-content-center align-items-center" style="max-width:70%">Discover where you all want to go next!</h2>
    </div>
    <%= image_tag "home_stepsKK3.png", style: "width:85vw; margin-inline:auto; margin-top:30px" %>
    <div class="cta-center">
      <h2 class="">Click Below To Get Started</h2>
      <a class="home-plus-button-primary" href="/groups"><i class="fa-solid fa-plus fa-xl" style="color: #ffffff;"></i></a>
    </div>
  </div>
</div>
<%console%>

app/views/home/index.html.erb
<div class="landing-page">
  <div class="landing-logo">
    <%= image_tag "KK_logo_H1_lg.png", style: "width: 50vw" %>
  </div>
  <div class="landing-text">
    Find the best place to travel, together
  </div>
  <div class="button-container">
    <div class="button">
      <div id="get-started">
        Get Started
      </div>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'index' %>
<%console%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kupukupu</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  </body>
</html>

app/views/memberships/_new_membership_form.html.erb
<div id="form_membership">
  <%= form_for(membership, url: group_memberships_path(@group)) do |f| %>
    <!-- First membership, use current user -->
    <% if @count == 0 %>
      <div class="form-group">
        <%= f.text_field :user_id, value: current_user.id, class: "form-control d-none" %>
      <%end%>
    </div>
    <div class="form-group">
      <%= f.label :departure %>
      <%= f.text_field :departure, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :travel_date, "Departure Date" %>
      <%= f.date_field :travel_date, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :return_date, "Return Date" %>
      <%= f.date_field :return_date, class: "form-control" %>
    </div>
    <div class="actions">
      <%= f.submit "Save", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/memberships/index.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-12">
      <%= link_to :back, class: "btn btn-secondary" do %>
        <i class="fa-solid fa-arrow-left"></i> Back
      <% end %>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-12">
      <h2>The travellers</h2>
      <% if @memberships.any? %>
        <ul class="list-group">
          <% @memberships.each do |membership| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              <%= membership.user.name %>
              <div>
                <%= link_to "Open", group_membership_path(group_id: @group.id, id: membership.id), class: "btn btn-info btn-sm" %>
              </div>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p>No travellers yet <%= link_to "Add a new traveler", new_group_membership_path %>.</p>
      <% end %>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-12">
      <%= link_to "Add a new traveller", new_group_membership_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>
<%console%>

app/views/memberships/new.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-12">
      <%= link_to groups_path, class: "btn btn-secondary" do %>
        <i class="fa-solid fa-arrow-left"></i> Back
      <% end %>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-12">
      <h2><%= @group.name %></h2>
      <%= render 'new_membership_form', membership: @membership %>
      <!-- Edit Group Name -->
    </div>
  </div>
</div>
<%console%>

app/views/memberships/show.html.erb
<div class="container">
  <div class="row my-3">
    <div class="col-12">
      <%= link_to groups_path, class: "btn btn-secondary" do %>
        <i class="fa-solid fa-arrow-left"></i> Back
      <% end %>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-12">
      <h2><%= @group.name %></h2>
      <ul class="list-group">
        <% @memberships.each do |membership| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <div class="d-flex align-items-center">
              <%= membership.user.name %>
              <%= link_to edit_group_membership_path(group_id: @group.id, id: membership.id), class: "ms-2" do %>
                <i class="fa fa-pen"></i>
              <% end %>
            </div>
            <div class="d-flex align-items-center">
              <%= membership.departure %>
              <%= link_to edit_group_membership_path(group_id: @group.id, id: membership.id), class: "ms-2" do %>
                <i class="fa fa-pen"></i>
              <% end %>
            </div>
            <div class="d-flex align-items-center">
              <%= membership.travel_date %>
              <%= link_to edit_group_membership_path(group_id: @group.id, id: membership.id), class: "ms-2" do %>
                <i class="fa fa-pen"></i>
              <% end %>
            </div>
            <div class="d-flex align-items-center">
              <%= membership.return_date %>
              <%= link_to edit_group_membership_path(group_id: @group.id, id: membership.id), class: "ms-2" do %>
                <i class="fa fa-pen"></i>
              <% end %>
            </div>
            <div class="d-flex align-items-center">
              <%= link_to edit_group_membership_path(group_id: @group.id, id: membership.id), class: "ms-2" do %>
                <i class="fa fa-trash"></i>
              <% end %>
            </div>
          </li>
        <% end %>
      </ul>
      <!-- Edit Group Name -->
      <div class="row my-3">
        <div class="col-12">
          <%= link_to "Add a new traveller", new_group_membership_path, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <%console%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag 'KK_logo_H1_lg.png', alt: 'Logo' %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Groups", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Friends", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>